/* Generated By:JJTree&JavaCC: Do not edit this line. JavaMMConstants.java */

package syntax;

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaMMConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BOOL = 7;
  /** RegularExpression Id. */
  int MAIN = 8;
  /** RegularExpression Id. */
  int VOID = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int INT = 11;
  /** RegularExpression Id. */
  int LPAREN = 12;
  /** RegularExpression Id. */
  int RPAREN = 13;
  /** RegularExpression Id. */
  int LBRACK = 14;
  /** RegularExpression Id. */
  int RBRACK = 15;
  /** RegularExpression Id. */
  int LBRACE = 16;
  /** RegularExpression Id. */
  int RBRACE = 17;
  /** RegularExpression Id. */
  int ADD = 18;
  /** RegularExpression Id. */
  int SUB = 19;
  /** RegularExpression Id. */
  int MUL = 20;
  /** RegularExpression Id. */
  int DIV = 21;
  /** RegularExpression Id. */
  int NOT = 22;
  /** RegularExpression Id. */
  int EQUAL = 23;
  /** RegularExpression Id. */
  int LOWER = 24;
  /** RegularExpression Id. */
  int BIGGER = 25;
  /** RegularExpression Id. */
  int AND = 26;
  /** RegularExpression Id. */
  int SEMI = 27;
  /** RegularExpression Id. */
  int COMMA = 28;
  /** RegularExpression Id. */
  int DOT = 29;
  /** RegularExpression Id. */
  int RETURN = 30;
  /** RegularExpression Id. */
  int PUBLIC = 31;
  /** RegularExpression Id. */
  int STAT = 32;
  /** RegularExpression Id. */
  int TRUE = 33;
  /** RegularExpression Id. */
  int FALSE = 34;
  /** RegularExpression Id. */
  int THIS = 35;
  /** RegularExpression Id. */
  int NEW = 36;
  /** RegularExpression Id. */
  int IF = 37;
  /** RegularExpression Id. */
  int ELSE = 38;
  /** RegularExpression Id. */
  int WHILE = 39;
  /** RegularExpression Id. */
  int CLASS = 40;
  /** RegularExpression Id. */
  int EXT = 41;
  /** RegularExpression Id. */
  int LENGTH = 42;
  /** RegularExpression Id. */
  int LITERAL = 43;
  /** RegularExpression Id. */
  int OCTAL = 44;
  /** RegularExpression Id. */
  int HEX = 45;
  /** RegularExpression Id. */
  int BINARY = 46;
  /** RegularExpression Id. */
  int INTEGER = 47;
  /** RegularExpression Id. */
  int IDENTIFIER = 48;
  /** RegularExpression Id. */
  int LETTER = 49;
  /** RegularExpression Id. */
  int DIGIT = 50;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"boolean\"",
    "\"main\"",
    "\"void\"",
    "\"String\"",
    "\"int\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"!\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"&&\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"return\"",
    "\"public\"",
    "\"static\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"new\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"class\"",
    "\"extends\"",
    "\"length\"",
    "<LITERAL>",
    "<OCTAL>",
    "<HEX>",
    "<BINARY>",
    "<INTEGER>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
